---
title: "MultiPart Diversity WCANN"
output: html_notebook
---
```{r setup}
library(data.table)
library(iNEXT)
library(vegan)
library(ggplot2)
library(tidyverse)
library(vegan)
library(betaC) #devtools::install_github("T-Engel/betaC")
library(cowplot)
theme_set(theme_cowplot())

wcann_full <- readRDS("wcann_data_gridded.RData")
wcann_distances.l <- readRDS("wcann_reg_distances.l.RData")
```

```{r summing abundances}
wcann <- wcann_full[,.(cell, year, matched_name2, wtcpue)][wtcpue >= 0]
wcann_summed <- wcann[,.(wtcpue_sum = sum(wtcpue)), .(cell, year, matched_name2)]

years<- unique(wcann_summed[,year])
sort(years)
```


Overall dissimilarity using betapart Multiple Site Diversity Metrics
```{r overall jaccard and bray dissimilarity}
dissimilarities_allyears_wcanngridcell <- as.data.table(matrix(nrow = length(years)))
dissimilarities_allyears_wcanngridcell[,year := as.numeric(V1)][,bray_dissimilarity := as.numeric(V1)][,bray_dissimilarity_balanced := as.numeric(V1)][,bray_dissimilarity_gradient := as.numeric(V1)][,jaccard_dissimilarity := as.numeric(V1)][,jaccard_dissimilarity_turnover := as.numeric(V1)][,jaccard_dissimilarity_nestedness := as.numeric(V1)][,V1 := NULL]

#Now loop through all years
for (i in 1:length(years)) {
  
  dissimilarities_allyears_wcanngridcell[i,year := years[i]]
  
  reduced_year <- wcann_summed[year == years[i],][,presence := ifelse(wtcpue_sum >0, 1, 0)]
  
  reduced_year_wide_abundance <- dcast(reduced_year, year + cell ~ matched_name2, value.var = "wtcpue_sum", fill = 0) #long to wide data for community matrix, column names are year, cell, then scientific 
  
  reduced_year_wide_abundance.bp <- betapart.core.abund(reduced_year_wide_abundance[,3:ncol(reduced_year_wide_abundance)])
  
  # sampling across equal sites
reduced_year_wide_abundance.sample <- beta.sample.abund(reduced_year_wide_abundance[,3:ncol(reduced_year_wide_abundance)], sites = nrow(reduced_year_wide_abundance), samples = 100)

  #combined bray dissimilarity
  dissimilarities_allyears_wcanngridcell[i, bray_dissimilarity := reduced_year_wide_abundance.sample$mean.values[[3]]]
  
  #balanced
  dissimilarities_allyears_wcanngridcell[i, bray_dissimilarity_balanced := reduced_year_wide_abundance.sample$mean.values[[1]]]
  
  #gradients
  dissimilarities_allyears_wcanngridcell[i, bray_dissimilarity_gradient := reduced_year_wide_abundance.sample$mean.values[[2]]]
  
  #AGAIN FOR OCCURRENCE
  reduced_year_wide_occurrence <- dcast(reduced_year, year + cell ~ matched_name2, value.var = "presence", fill = 0) #long to wide data for community matrix, column names are year, cell, then scientific
  
    reduced_year_wide_occurrence.bp <- betapart.core(reduced_year_wide_occurrence[,3:ncol(reduced_year_wide_occurrence)])
  
  # sampling across equal sites
reduced_year_wide_occurrence.sample <- beta.sample(reduced_year_wide_occurrence[,3:ncol(reduced_year_wide_occurrence)], sites = nrow(reduced_year_wide_occurrence), samples = 100, index.family = "jac")

  #combined jaccard dissimilarity
  dissimilarities_allyears_wcanngridcell[i, jaccard_dissimilarity := reduced_year_wide_occurrence.sample$mean.values[[3]]]
  
  #balanced
  dissimilarities_allyears_wcanngridcell[i, jaccard_dissimilarity_turnover := reduced_year_wide_occurrence.sample$mean.values[[1]]]
  
  #gradients
  dissimilarities_allyears_wcanngridcell[i, jaccard_dissimilarity_nestedness := reduced_year_wide_occurrence.sample$mean.values[[2]]]
  
}

saveRDS(dissimilarities_allyears_wcanngridcell, "dissimilarities_allyears_wcanngridcell.RData")

#most of beta diversity derived from turnover
ggplot(data = dissimilarities_allyears_wcanngridcell, aes(year)) +
  geom_line(aes(y = 1-bray_dissimilarity), color = "purple", linetype = 2) + #bray, overall, dotted purple
  geom_line(aes(y = 1-bray_dissimilarity_balanced), color = "darkgreen", linetype = 2) + #bray, turnover, dotted green
  geom_line(aes(y = 1-jaccard_dissimilarity), color = "purple", linetype = 1) + #jaccard, overall, straight purple
  geom_line(aes(y = 1-jaccard_dissimilarity_turnover), color = "darkgreen", linetype = 1) +#jaccard, turnover, straight green
  lims(y = c(0.05, 0.27)) +
  labs(y = "Similarity", x = "Year") +
  theme_classic()


```