---
title: "Figure Visualization Homogenization, Differentiation, and Stability"
output: html_notebook
---

Figure 1 script part 1 for Kitchel et al. 2023 in prep taxonomic diversity manuscript.

```{r setup}
library(data.table)
library(vegan)
library(sf)
library(concaveman) #polygon around points
library(betapart) #allows us to partition beta diversity
library(geosphere)
library(ggpubr) #stat_regline_equation
library(nlme)
library(cowplot)

```

Load Data
```{r}
FishGlob_clean <- readRDS(here::here("data", "cleaned", "FishGlob_clean.rds"))

```

Examples:

Homogenization: "SEUS-summer"
Year 4 versus 6th to final 
```{r seus summer contrast plot mds}
seus_years <- unique(FishGlob_clean[survey_unit == "SEUS-summer",year])
#year 4 = 1993,  final year = 2019

seus_summer <- FishGlob_clean[survey_unit == "SEUS-summer" & year %in% c(1993,2019),]

#1993
seus_1993 <- dcast(seus_summer[year == 1993,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
seus_1993.communitymatrix <- seus_1993[, 3:ncol(seus_1993)] #community matrix

#construct ordination

seus_1993_mds <- metaMDS(seus_1993.communitymatrix)

seus_1993_mds_plot <- ordiplot(seus_1993_mds, choices=c(1,2))

seus_1993_mds.dt <- data.table(seus_1993_mds_plot$sites)

seus_1993_mds.dt[,survey_unit := "SEUS-summer"][,year := 1993]

#2019
seus_2019 <- dcast(seus_summer[year == 2019,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
seus_2019.communitymatrix <- seus_2019[, 3:ncol(seus_2019)] #community matrix

#construct ordination

seus_2019_mds <- metaMDS(seus_2019.communitymatrix)

seus_2019_mds_plot <- ordiplot(seus_2019_mds, choices=c(1,2))

seus_2019_mds.dt <- data.table(seus_2019_mds_plot$sites)

seus_2019_mds.dt[,survey_unit := "SEUS-summer"][,year := 2019]

seus_full_mds.dt <- rbind(seus_1993_mds.dt, seus_2019_mds.dt)

seus_summer_mds_contrast <- ggplot(data = seus_full_mds.dt) +
  geom_point(aes(x = NMDS1, y = NMDS2), color = "#e7ac5b") +
  stat_ellipse(aes(x = NMDS1, y = NMDS2)) +
  facet_wrap(~year)+
  theme_classic()

seus_summer_mds_contrast
```

Differentiation: "NZ-WCSI" "#AAF400"
Year 1 versus to final 
```{r}
nz_wcsi_years <- unique(FishGlob_clean[survey_unit == "NZ-WCSI",year])
#year 1 = 2000,  final year = 2019

nz_wcsi <- FishGlob_clean[survey_unit == "NZ-WCSI" & year %in% c(2000,2019),]

#2000
nz_wcsi_2000 <- dcast(nz_wcsi[year == 2000,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
nz_wcsi_2000.communitymatrix <- nz_wcsi_2000[, 3:ncol(nz_wcsi_2000)] #community matrix

#construct ordination

nz_wcsi_2000_mds <- metaMDS(nz_wcsi_2000.communitymatrix)

nz_wcsi_2000_mds_plot <- ordiplot(nz_wcsi_2000_mds, choices=c(1,2))

nz_wcsi_2000_mds.dt <- data.table(nz_wcsi_2000_mds_plot$sites)

nz_wcsi_2000_mds.dt[,survey_unit := "NZ-WCSI"][,year := 2000]

#2019
nz_wcsi_2019 <- dcast(nz_wcsi[year == 2019,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
nz_wcsi_2019.communitymatrix <- nz_wcsi_2019[, 3:ncol(nz_wcsi_2019)] #community matrix

#construct ordination

nz_wcsi_2019_mds <- metaMDS(nz_wcsi_2019.communitymatrix)

nz_wcsi_2019_mds_plot <- ordiplot(nz_wcsi_2019_mds, choices=c(1,2))

nz_wcsi_2019_mds.dt <- data.table(nz_wcsi_2019_mds_plot$sites)

nz_wcsi_2019_mds.dt[,survey_unit := "NZ-WCSI"][,year := 2019]

nz_wcsi_full_mds.dt <- rbind(nz_wcsi_2000_mds.dt, nz_wcsi_2019_mds.dt)

nz_wcsi_mds_contrast <- ggplot(data = nz_wcsi_full_mds.dt) +
  geom_point(aes(x = NMDS1, y = NMDS2), color = "#91c874") +
  stat_ellipse(aes(x = NMDS1, y = NMDS2)) +
  facet_wrap(~year)+
  theme_classic()

nz_wcsi_mds_contrast
```

Stable: "SCS-SUMMER"
Year 2 in series vs final year 
```{r}
scs_summer_years <- unique(FishGlob_clean[survey_unit == "SCS-SUMMER",year])
#year 2 = 1988,  final year = 2019

scs_summer <- FishGlob_clean[survey_unit == "SCS-SUMMER" & year %in% c(1988,2019),]

#1988
scs_summer_1988 <- dcast(scs_summer[year == 1988,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
scs_summer_1988.communitymatrix <- scs_summer_1988[, 3:ncol(scs_summer_1988)] #community matrix

#construct ordination

scs_summer_1988_mds <- metaMDS(scs_summer_1988.communitymatrix)

scs_summer_1988_mds_plot <- ordiplot(scs_summer_1988_mds, choices=c(1,2))

scs_summer_1988_mds.dt <- data.table(scs_summer_1988_mds_plot$sites)

scs_summer_1988_mds.dt[,survey_unit := "SCS-SUMMER"][,year := 1988]

#2019
scs_summer_2019 <- dcast(scs_summer[year == 2019,],  haul_id + year ~ accepted_name,  value.var = "wgt_cpue",  fun.aggregate = sum) #longitude to wide data for community matrix,  column names are cell then species
              
scs_summer_2019.communitymatrix <- scs_summer_2019[, 3:ncol(scs_summer_2019)] #community matrix

#construct ordination

scs_summer_2019_mds <- metaMDS(scs_summer_2019.communitymatrix)

scs_summer_2019_mds_plot <- ordiplot(scs_summer_2019_mds, choices=c(1,2))

scs_summer_2019_mds.dt <- data.table(scs_summer_2019_mds_plot$sites)

scs_summer_2019_mds.dt[,survey_unit := "SCS-SUMMER"][,year := 2019]

scs_summer_full_mds.dt <- rbind(scs_summer_1988_mds.dt, scs_summer_2019_mds.dt)

scs_summer_mds_contrast <- ggplot(data = scs_summer_full_mds.dt) +
  geom_point(aes(x = NMDS1, y = NMDS2), color = "#cbbfde") +
  stat_ellipse(aes(x = NMDS1, y = NMDS2)) +
  facet_wrap(~year)+
  theme_classic()

scs_summer_mds_contrast
```

Merge Data Tables to Ease Plotting in Ggplot
```{r}
full_mds.dt <- rbind(scs_summer_full_mds.dt, nz_wcsi_full_mds.dt, seus_full_mds.dt)

name_key <- data.table(survey_unit = c("NZ-WCSI","SEUS-summer","SCS-SUMMER"),`Survey Unit` = c("W Coast S Island, NZ","SE US Summer","Scotian Shelf, CA"))

full_mds.dt <- full_mds.dt[name_key, on = "survey_unit"]

#mark years as early and late
full_mds.dt[,`Time period`:= ifelse(year==min(year),"Early","Late"),.(survey_unit)]

#change factor order to match other components of manuscript
full_mds.dt[,`Survey Unit` := factor(`Survey Unit`, levels = c("W Coast S Island, NZ","SE US Summer","Scotian Shelf, CA"), labels = c("West Coast South Island\nNew Zealand","Southeast United\nStates Summer","Scotian Shelf\nCanada"))]

mds_contrast_noannotate <- ggplot(data = full_mds.dt) +
  geom_point(aes(x = NMDS1, y = NMDS2, fill = `Survey Unit`, color = factor(`Time period`)), size = 2, shape = 21) +
  stat_ellipse(aes(x = NMDS1, y = NMDS2,linetype=`Time period`)) +
  facet_wrap(vars(`Survey Unit`), nrow = 1) +
  scale_fill_manual(values = c("#91c874","#e7ac5b", "#cbbfde")) +
  scale_color_manual(values=c("white","black")) +
  scale_linetype_manual(values = c("dotted","solid")) +
  theme_classic() +
  theme(legend.position = "null")

 
mds_contrast <- ggdraw(xlim = c(0,3), ylim = c(0,1.1)) +
draw_plot(x = 0, y = 0,mds_contrast_noannotate, width = 3, height = 1) +
geom_text(x = 1.01, y = 1.05,aes(label = "Early year")) +
geom_text(x = 1.9, y = 1.05,aes(label = "Late year")) +
geom_text(x = 0.3, y = 0.905,aes(label = "b.", fontface="bold")) +
geom_text(x = 1.23, y = 0.905,aes(label = "c.", fontface="bold")) +
geom_text(x = 2.14, y = 0.905,aes(label = "d.", fontface="bold")) +
geom_segment(aes(x = 1.3, y = 1.05, yend = 1.05, xend =1.6),linetype = "dotted") +
geom_segment(aes(x = 2.1, y = 1.05, yend = 1.05, xend =2.4))  

mds_contrast

ggsave(mds_contrast, path = here::here("figures"), filename = "mds_contrast.jpg",
       height = 3, width = 9, unit = "in")

saveRDS(mds_contrast, here::here("figures","mds_contrast.rds"))
```


