---
title: "Setup North American Trawl Data"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(data.table)
library(ggplot2)
```

## Download data from Ocean Adapt
```{r import data from Ocean Adapt on GitHub}

trawl <- readRDS(url('https://raw.githubusercontent.com/pinskylab/OceanAdapt/master/data_clean/all-regions-full.rds'))
trawl <- data.table(trawl)
```

# Plot taxa by region by year to look for taxa that aren't recorded consistently
```{r plot species by region by year, fig.height = 16, fig.width = 3}
sppbyyr <- trawl[, .(pres = length(spp)), by = .(region, year, spp)]
regs <- sppbyyr[, sort(unique(region))]

# loop through each region and make a plot
for(i in 1:length(regs)){
  p1 <- ggplot(sppbyyr[region == regs[i]], aes(x = year, y = spp, group = spp)) +
    geom_line(size = 0.2) +
    geom_point(size = 0.2) +
    theme(text=element_text(size = 3), 
          axis.text.x = element_text(angle = 90),
          strip.text.x = element_text(size = 5)) +
    ggtitle(regs[i])
  print(p1)
}

```

### Trim out species not recorded consistently
```{r trim species}
# remove trash species
trawl <- trawl[spp != 'Trash species', ]

```

### Save out
```{r save}
saveRDS(trawl, file = "data/NorthAmerican_trawl_data_full.rds")
```

