---
title: "NEUS Distance Decay over Time"
output: html_notebook
---

```{r setup}
library(data.table)
library(vegan)
library(ggplot2)
library(broom) #augment
library(betapart)
library(geosphere)

#load spring and fall data
dat_NEUS_grid.spring.reduced_3plustows <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/dat_NEUS_grid.spring.reduced_3plustows.RData")

dat_NEUS_grid.fall.reduced_3plustows <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/dat_NEUS_grid.fall.reduced_3plustows.RData")

#distance among grid cells
neus_reg_distances_fall.l <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/neus_reg_distances_fall.l.RData")

neus_reg_distances_spring.l <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/neus_reg_distances_spring.l.RData")


```

In this iteration of the analysis, each tow will be analyzed independently--I will not be summing or averaging over cells. However, I did use cells in order to eliminate undersampled years/tows.


Distance decay for SPRING NEUS
```{r each year build exponential model for spring}

#years
#order data table by years
dat_NEUS_grid.spring.reduced_3plustows[,year:= as.numeric(year)] #make numeric
setorder(dat_NEUS_grid.spring.reduced_3plustows, year)

neus_years_spring <- unique(dat_NEUS_grid.spring.reduced_3plustows[,year])

neus_similarity_mod_coefs <- data.table("year" = neus_years_spring, "jaccard_total_initial_sim" = 0, "jaccard_total_halving" = 0, "jaccard_turnover_initial_sim" = 0, "jaccard_turnover_halving" = 0, "bray_total_initial_sim" = 0, "bray_total_halving" = 0, "bray_balanced_initial_sim" = 0, "bray_balanced_halving" = 0)


for (i in 1:length(neus_years_spring)) {
  
  neus_similarity_mod_coefs[i,"year"] <- neus_years_spring[i]
  
  reduced_year <- dat_NEUS_grid.spring.reduced_3plustows[year == neus_years_spring[i],]
  
  #distances among cells
  setorder(reduced_year, haulid)
  
  lat_lon_haulid <- unique(reduced_year[,.(lat,lon,haulid)])
  
  distances <- distm(lat_lon_haulid[,.(lon, lat)])
  
  distances.dist <- as.dist(distances)
  
  #throw to wide
  
  reduced_year_wide <- dcast(reduced_year, haulid ~ matched_name2, value.var = "wtcpue", fill = 0, fun.aggregate = sum) #long to wide data for community matrix, column names are cell then species
  
#for presence absense matrix, all values !=0 are 1s
index <- reduced_year_wide[,1]
spp_only <- reduced_year_wide[,2:ncol(reduced_year_wide)]

spp_only[spp_only > 0] <- as.numeric(1)

reduced_year_wide.pres <- cbind(index, spp_only)

#now, use betapart to construct objects to be used in decay models

beta.pair.abund <- beta.pair.abund(reduced_year_wide[,2:ncol(reduced_year_wide)], index.family = "bray") #abundances

beta.pair <- beta.pair(reduced_year_wide.pres[,2:ncol(reduced_year_wide.pres)], index.family = "jaccard") #occurences


#ABUNDANCE

#bray balanced (turnover), fitting glm because I can't get betapart to work (no initializing values)
  s = 1-as.vector(beta.pair.abund$beta.bray.bal)
  d = as.vector(distances.dist)
  g = suppressWarnings(glm(s~d,family=binomial(link='log')))
    
        Coefs_braybalanced=coef(g)
        
        neus_similarity_mod_coefs[i,"bray_balanced_initial_sim"] <- exp(Coefs_braybalanced[1])
        neus_similarity_mod_coefs[i,"bray_balanced_halving"] <- log(0.5)/Coefs_braybalanced[2]
  
  
#bray total (nestedness and turnover)  
  s = 1-as.vector(beta.pair.abund$beta.bray)
  d = as.vector(distances.dist)
  g = suppressWarnings(glm(s~d,family=binomial(link='log')))
    
        Coefs_braytotal=coef(g)
        
        neus_similarity_mod_coefs[i,"bray_total_initial_sim"] <- exp(Coefs_braytotal[1])
        neus_similarity_mod_coefs[i,"bray_total_halving"] <- log(0.5)/Coefs_braytotal[2]
  
  
  #OCCURRENCE
  #jaccard turnover
   s = 1-as.vector(beta.pair$beta.jtu)
  d = as.vector(distances.dist)
  g = suppressWarnings(glm(s~d,family=binomial(link='log')))
    
        Coefs_jaccardturnover=coef(g)
        
        neus_similarity_mod_coefs[i,"jaccard_turnover_initial_sim"] <- exp(Coefs_jaccardturnover[1])
        neus_similarity_mod_coefs[i,"jaccard_turnover_halving"] <- log(0.5)/Coefs_jaccardturnover[2]
  
  #total jaccard from pres abs data
  s = 1-as.vector(beta.pair$beta.jac)
  d = as.vector(distances.dist)
  g = suppressWarnings(glm(s~d,family=binomial(link='log')))
    
        Coefs_jaccardtotal=coef(g)
        
        neus_similarity_mod_coefs[i,"jaccard_total_initial_sim"] <- exp(Coefs_jaccardtotal[1])
        neus_similarity_mod_coefs[i,"jaccard_total_halving"] <- log(0.5)/Coefs_jaccardtotal[2]

      print(paste0(i,"/",neus_years_spring[i]))
  }
  
#to make null model, randomize years
neus_years_spring

null1 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)
null2 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)
null3 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)
null4 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)
null5 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)
null6 <- sample(neus_years_spring, size = length(neus_years_spring), replace = F)

null <- data.table(null1, null2, null3, null4, null5, null6)

neus_similarity_mod_coefs_withnull <- cbind(neus_similarity_mod_coefs, null)

ggplot(data = neus_similarity_mod_coefs_withnull) +
  #nulls
    geom_smooth(aes(x=as.numeric(null1), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null1), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null2), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null2), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null3), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null3), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null4), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null4), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null5), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null5), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null6), y = jaccard_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null6), y = jaccard_turnover_halving), linetype = 1, color = "aliceblue", se = F) +
    #geom_point(aes(x=as.numeric(year), y = jaccard_total_halving), shape = 15) +
  geom_smooth(aes(x=as.numeric(year), y = jaccard_total_halving), linetype = 2, color = "black", se = F) +
  #geom_point(aes(x=as.numeric(year), y = jaccard_turnover_halving), shape = 15, color = "green") +
  geom_smooth(aes(x=as.numeric(year), y = jaccard_turnover_halving), linetype = 1, color = "black", se = F) +
  
  labs(x = "Year", y = "Jaccard Similarity Halving Distance (m)") +
  theme_classic() +
  theme(text = element_text(size = 13))

#bray, abundance
ggplot(data = neus_similarity_mod_coefs_withnull) +
  #nulls
    geom_smooth(aes(x=as.numeric(null1), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null1), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null2), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null2), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null3), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null3), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null4), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null4), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null5), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null5), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null6), y = bray_total_halving), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null6), y = bray_balanced_halving), linetype = 1, color = "aliceblue", se = F) +
    #geom_point(aes(x=as.numeric(year), y = bray_total_halving), shape = 15) +
  geom_smooth(aes(x=as.numeric(year), y = bray_total_halving), linetype = 2, color = "black", se = F) +
  #geom_point(aes(x=as.numeric(year), y = bray_balanced_halving), shape = 15, color = "green") +
  geom_smooth(aes(x=as.numeric(year), y = bray_balanced_halving), linetype = 1, color = "black", se = F) +
  
  labs(x = "Year", y = "Bray Similarity Halving Distance (m)") +
  theme_classic() +
  theme(text = element_text(size = 13))

ggsave(path = "plots", file = "slopes_for_distance_decay.jpg", width = 6, height = 4, unit = "in")


#initial similarity over time
ggplot(data = neus_similarity_mod_coefs_withnull) +
  #nulls
    geom_smooth(aes(x=as.numeric(null1), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null1), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null2), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null2), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null3), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null3), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null4), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null4), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null5), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null5), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null6), y = jaccard_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null6), y = jaccard_turnover_initial_sim), linetype = 1, color = "aliceblue", se = F) +
    #geom_point(aes(x=as.numeric(year), y = jaccard_total_initial_sim), shape = 15) +
  geom_smooth(aes(x=as.numeric(year), y = jaccard_total_initial_sim), linetype = 2, color = "black", se = F) +
  #geom_point(aes(x=as.numeric(year), y = jaccard_turnover_initial_sim), shape = 15, color = "green") +
  geom_smooth(aes(x=as.numeric(year), y = jaccard_turnover_initial_sim), linetype = 1, color = "black", se = F) +
  
  labs(x = "Year", y = "Jaccard Initial Similarity Distance (m)") +
  theme_classic() +
  theme(text = element_text(size = 13))

#bray, abundance
ggplot(data = neus_similarity_mod_coefs_withnull) +
  #nulls
    geom_smooth(aes(x=as.numeric(null1), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null1), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null2), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null2), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null3), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null3), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null4), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null4), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null5), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null5), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
  
      geom_smooth(aes(x=as.numeric(null6), y = bray_total_initial_sim), linetype = 2, color = "aliceblue", se = F) +
  geom_smooth(aes(x=as.numeric(null6), y = bray_balanced_initial_sim), linetype = 1, color = "aliceblue", se = F) +
    #geom_point(aes(x=as.numeric(year), y = bray_total_initial_sim), shape = 15) +
  geom_smooth(aes(x=as.numeric(year), y = bray_total_initial_sim), linetype = 2, color = "black", se = F) +
  #geom_point(aes(x=as.numeric(year), y = bray_balanced_initial_sim), shape = 15, color = "green") +
  geom_smooth(aes(x=as.numeric(year), y = bray_balanced_initial_sim), linetype = 1, color = "black", se = F) +
  
  labs(x = "Year", y = "Bray Initial Similarity Distance (m)") +
  theme_classic() +
  theme(text = element_text(size = 13))
```