---
title: "Plot of 3 regions for meeting"
output: html_notebook
---

```{r setup}
library(dggridR)
library(data.table)
library(rgdal)
library(raster)
library(sp)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(taxize) #standardizing names
library(geosphere)  #to calculate distance between lat lon of grid cells

#tow points
unique_neus_latlon <- readRDS("unique_neus_latlon.RData")
unique_wcann_latlon <- readRDS("unique_wcann_latlon.RData")
unique_EBS_latlon <- readRDS("unique_EBS_latlon.RData")
unique_wctri_latlon <- readRDS("uniqee_wctri_latlon.RData")

dat_EBS_grid.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-EBS/dat_EBS_grid.reduced_3plustows.rds")
unique_EBS_latlon <- unique(dat_EBS_grid.reduced_3plustows[,.(lat,lon)])
dat_NEUS_grid.fall.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/dat_NEUS_grid.fall.reduced_3plustows.RData")
dat_NEUS_grid.spring.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/dat_NEUS_grid.spring.reduced_3plustows.RData")
unique_NEUS_latlon <- unique(rbind(dat_NEUS_grid.spring.reduced_3plustows[,.(lat,lon)], dat_NEUS_grid.fall.reduced_3plustows[,.(lat,lon)]))

dat_WCTRI_grid.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-WCTRI/dat_WCTRI_grid.reduced_3plustows.rds")
unique_WCTRI_latlon <- unique(dat_WCTRI_grid.reduced_3plustows[,.(lat,lon)])

dat_WCANN_grid.reduced <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-WCANN/dat_WCANN_grid.reduced.rds")
unique_WCANN_latlon <- unique(dat_WCANN_grid.reduced[,.(lat,lon)])

dat_SHELF_grid.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-SHELF/dat_SHELF_grid.reduced_3plustows.rds")
unique_SHELF_latlon <- unique(dat_SHELF_grid.reduced_3plustows[,.(lat,lon)])

dat_SA_grid.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-SA/dat_SA_grid.reduced_3plustows.rds")
unique_SA_latlon <- unique(dat_SA_grid.reduced_3plustows[,.(lat,lon)])

dat_GMEX_grid.reduced_3plustows <- readRDS("~/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-GMEX/dat_GMEX_grid.reduced_3plustows.rds")
unique_GMEX_latlon <- unique(dat_GMEX_grid.reduced_3plustows[,.(lat,lon)])



#cell grids
grid_neus <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_neus.RData")
grid_ebs <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_ebs.rds")
grid_gmex <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_gmex.rds")
grid_wcann <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_wcann.rds")
grid_wctri <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_wctri.rds")
grid_sa <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_sa.rds")
grid_shelf <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/scale_exploration/grid_prep_code/grid_shelf.rds")

```

```{r make plot}
#plot north america
world <- ne_countries(scale = "medium", returnclass = "sp")

world_ext <- extent(-180, -51.5,23, 67)

north_america_spdf <- crop(world, world_ext)

north_america_df <- fortify(north_america_spdf)

na_outline <- ggplot(north_america_df, aes(long, lat, group = group)) +
  geom_polygon(color = "white", fill = "grey") +
  labs(x = "Longitude", y = "Latitude") +
  coord_equal() +
  theme_classic() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
 geom_point(unique_WCANN_latlon, mapping = aes(lon, lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "red") +
    geom_point(unique_NEUS_latlon, mapping = aes(lon, lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "orange") +
    geom_point(unique_EBS_latlon, mapping = aes(lon, lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "green") +
    geom_point(unique_SHELF_latlon, mapping = aes(lon,lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "blue") +
      geom_point(unique_WCTRI_latlon, mapping = aes(lon,lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "violet") +
          geom_point(unique_SA_latlon, mapping = aes(lon,lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "purple") +
          geom_point(unique_GMEX_latlon, mapping = aes(lon,lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "black")
  
  
  #+
    geom_polygon(grid_ebs, mapping = aes(x = lon,y = lat.x, group = cell), inherit.aes = FALSE, color = "black", fill = NA, size = 0.1) +
    geom_polygon(grid_neus, mapping = aes(x = lon,y = lat, group = cell), inherit.aes = FALSE, color = "black", fill = NA, size = 0.1) +
    geom_polygon(grid_wcann, mapping = aes(x = long,y = lat.x, group = cell), inherit.aes = FALSE, color = "black", fill = NA, size = 0.1) +
  coord_equal())
```
Plot Just NEUS
```{r}
#Just NEUS
ggplot(north_america_df, aes(long, lat, group = group)) +
  geom_polygon(color = "white", fill = "grey") +
  labs(x = "Longitude", y = "Latitude") +
  coord_equal() +
  theme_classic() +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0)) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1)) +
    geom_point(unique_NEUS_latlon, mapping = aes(lon, lat), inherit.aes = FALSE, shape = 18, size = 0.001, color = "orange") +
    lims(x = c(-80,-60), y = c(30,48))

```

