---
title: "Dissimilarity Temperature Regression for All Regions"
output: html_notebook
---

Here we will finally link temperature to dissimilarity

NEXT STEP: Instead of absolute temperature, look at temperature anomolies 

```{r setup}

library(data.table)
library(ggplot2)
library(lme4)
library(lmerTest)


OISST_data_temp_avgs_full <- readRDS(here::here("data","Temperature","OISST_data_temp_avgs_full.rds"))

#switch year to numeric
OISST_data_temp_avgs_full[, year:= as.numeric(as.character(year_for_avg))][, season_survey := as.character(survey_season)][,season := NULL][,survey := NULL]

#pull in average distance decay values
distances_dissimilarities_allyears.year.models <- readRDS(here::here("output","distance_decay","distances_dissimilarities_allyears.year.models.rds"))

```

Not matching, check structure
```{r}
str(distances_dissimilarities_allyears.year.models[,.(year,season_survey,season,survey)])
str(OISST_data_temp_avgs_full[,.(year,season_survey,season,survey)])
```


Put into one data table
```{r link temp to avg values}
distances_dissimilarities_allyears.year.models.temp <- OISST_data_temp_avgs_full[distances_dissimilarities_allyears.year.models, on = c("year","season_survey")]
```

Plotting with temp

```{r EBS temp}

#for just EBS
ebs_dissimilarity_temperature_mean <- ggplot(data = distances_dissimilarities_allyears.year.models.temp[season_survey == "EBS_NA",]) +
  geom_smooth(aes(x = sst_mean, y = mean_yearly_bray), method = "lm", se = F, color  = "#3B00FB") +
  labs(x = "Mean Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_mean, y = mean_yearly_bray), color  = "#3B00FB", alpha = 0.3) +
  theme_classic()

ggsave(ebs_dissimilarity_temperature_mean, path  = here::here("figures","distance_decay"), filename = "ebs_dissimilarity_temperature_mean.jpg") 

ebs_dissimilarity_temperature_mean_mod <- lm(mean_yearly_bray ~ sst_mean, data = distances_dissimilarities_allyears.year.models.temp[season_survey == "EBS_NA",])

summary(ebs_dissimilarity_temperature_mean_mod)

#for just EBS
ebs_dissimilarity_temperature_max <- ggplot(data = distances_dissimilarities_allyears.year.models.temp[season_survey == "EBS_NA",]) +
  geom_smooth(aes(x = sst_max, y = mean_yearly_bray), method = "lm", se = F, color  = "#C4451C") +
  labs(x = "Maximum Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_max, y = mean_yearly_bray), color  = "#C4451C", alpha = 0.3) +
  theme_classic()

ggsave(ebs_dissimilarity_temperature_max, path  = here::here("figures","distance_decay"), filename = "ebs_dissimilarity_temperature_max.jpg") 

#for just EBS
ebs_dissimilarity_temperature_min <- ggplot(data = distances_dissimilarities_allyears.year.models.temp[season_survey == "EBS_NA",]) +
  geom_smooth(aes(x = sst_min, y = mean_yearly_bray), method = "lm", se = F, color  ="#325A9B") +
  labs(x = "Minimum Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_min, y = mean_yearly_bray), color  ="#325A9B", alpha = 0.3) +
  theme_classic()

ggsave(ebs_dissimilarity_temperature_min, path  = here::here("figures","distance_decay"), filename = "ebs_dissimilarity_temperature_min.jpg") 

#for just EBS
ebs_dissimilarity_temperature_SD <- ggplot(data = distances_dissimilarities_allyears.year.models.temp[season_survey == "EBS_NA",]) +
  geom_smooth(aes(x = sst_SD, y = mean_yearly_bray), method = "gam", se = F, color  ="#C075A6") +
  labs(x = "Standard Deviation SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_SD, y = mean_yearly_bray), color  = "#C075A6", alpha = 0.3) +
  theme_classic()

ggsave(ebs_dissimilarity_temperature_SD, path  = here::here("figures","distance_decay"), filename = "ebs_dissimilarity_temperature_SD.jpg") 
```

How does this trend hold up for all regions?
```{r temp all regions}
#for all regions
allreg_dissimilarity_temperature_mean <- ggplot(data = distances_dissimilarities_allyears.year.models.temp) +
  labs(x = "Mean Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_mean, y = mean_yearly_bray, color = season_survey), alpha = 0.3) +
  geom_line(aes(x = sst_mean, y = mean_yearly_bray, color = season_survey), stat="smooth", method = "lm") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = sst_mean, y = mean_yearly_bray), method = "lm", se = F, color  = "black") +
  theme_classic()

ggsave(allreg_dissimilarity_temperature_mean, path  = here::here("figures","distance_decay"), filename = "allreg_dissimilarity_temperature_mean.jpg", height = 4, width = 9, unit = "in") 

allreg_dissimilarity_temperature_mean_mod <- lmer(mean_yearly_bray ~ sst_mean + (1|season_survey), data = distances_dissimilarities_allyears.year.models.temp)

summary(allreg_dissimilarity_temperature_mean_mod)

#minimum all regions
allreg_dissimilarity_temperature_min <- ggplot(data = distances_dissimilarities_allyears.year.models.temp) +
  labs(x = "Minimum Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_min, y = mean_yearly_bray, color = season_survey), alpha = 0.3) +
  geom_line(aes(x = sst_min, y = mean_yearly_bray, color = season_survey), stat="smooth", method = "lm") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = sst_min, y = mean_yearly_bray), method = "lm", se = F, color  = "black") +
  theme_classic()

ggsave(allreg_dissimilarity_temperature_min, path  = here::here("figures","distance_decay"), filename = "allreg_dissimilarity_temperature_min.jpg", height = 4, width = 9, unit = "in") 

allreg_dissimilarity_temperature_min_mod <- lmer(mean_yearly_bray ~ sst_min + (1|season_survey), data = distances_dissimilarities_allyears.year.models.temp)

summary(allreg_dissimilarity_temperature_min_mod)

#maximum for all regions
allreg_dissimilarity_temperature_max <- ggplot(data = distances_dissimilarities_allyears.year.models.temp) +
  labs(x = "Maximum Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_max, y = mean_yearly_bray, color = season_survey), alpha = 0.3) +
  geom_line(aes(x = sst_max, y = mean_yearly_bray, color = season_survey), stat="smooth", method = "lm") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = sst_max, y = mean_yearly_bray), method = "lm", se = F, color  = "black") +
  theme_classic()

ggsave(allreg_dissimilarity_temperature_max, path  = here::here("figures","distance_decay"), filename = "allreg_dissimilarity_temperature_max.jpg", height = 4, width = 9, unit = "in") 

allreg_dissimilarity_temperature_max_mod <- lmer(mean_yearly_bray ~ sst_max + (1|season_survey), data = distances_dissimilarities_allyears.year.models.temp)

summary(allreg_dissimilarity_temperature_max_mod)

#SD all reg
allreg_dissimilarity_temperature_SD <- ggplot(data = distances_dissimilarities_allyears.year.models.temp) +
  labs(x = "SD of Annual SST (˚C)",  y = "Average Bray Curtis Dissimilarity") +
  geom_point(aes(x = sst_SD, y = mean_yearly_bray, color = season_survey), alpha = 0.3) +
  geom_line(aes(x = sst_SD, y = mean_yearly_bray, color = season_survey), stat="smooth", method = "lm") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = sst_SD, y = mean_yearly_bray), method = "lm", se = F, color  = "black") +
  theme_classic()

ggsave(allreg_dissimilarity_temperature_SD, path  = here::here("figures","distance_decay"), filename = "allreg_dissimilarity_temperature_SD.jpg", height = 4, width = 9, unit = "in") 

allreg_dissimilarity_temperature_SD_mod <- lmer(mean_yearly_bray ~ sst_SD + (1|season_survey), data = distances_dissimilarities_allyears.year.models.temp)

summary(allreg_dissimilarity_temperature_SD_mod)
```

