---
title: "NEUS_fall_similarity_heatmap_distance"
output: html_notebook
---

```{r setup}
library(data.table)
library(viridis)
library(ggplot2)
library(reshape2)
library(geosphere)
library(vegan)
library(raster)

#load fall data

dat_NEUS_grid.fall.reduced_3plustows <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/dat_NEUS_grid.fall.reduced_3plustows.RData")

#distance among grid cells
neus_reg_distances_fall.l <- readRDS("/Users/zoekitchel/Documents/grad school/Rutgers/Repositories/trawl_spatial_turnover/data/gridded/USA-NEUS/neus_reg_distances_fall.l.RData")


```
Lists of Years
```{r year lists}

#fall
dat_NEUS_grid.fall.reduced_3plustows[,year:= as.numeric(year)] #make numeric
setorder(dat_NEUS_grid.fall.reduced_3plustows, year)

neus_years_fall <- unique(dat_NEUS_grid.fall.reduced_3plustows[,year])
```

Haul ID keys
```{r list of haulids}

neus_fall_haulids <- unique(dat_NEUS_grid.fall.reduced_3plustows[,haulid])
neus_fall_haulids_key <- data.table(haulid = neus_fall_haulids, key_ID = seq(1,length(neus_fall_haulids), by = 1))
```

Convert haulids to numeric key_IDs
```{r}

#fall
dat_NEUS_grid.fall.reduced_3plustows <- dat_NEUS_grid.fall.reduced_3plustows[neus_fall_haulids_key, on = "haulid"]
```


Dissimilarities across multiple years
FALL
```{r dissimilarities between cells across multiple years for fall}
neus_fall_distances_dissimilarities_allyears <- data.table("haulid1" = integer(), "haulid2" = integer(), "distance" = numeric(),"bray_curtis_dissimilarity" = numeric(), year = integer(), "jaccard_dissimilarity" = numeric())

#Now loop through all years
for (i in 1:length(neus_years_fall)) {
  reduced_year <- dat_NEUS_grid.fall.reduced_3plustows[year == neus_years_fall[i],]
  
  #distances among cells
  setorder(reduced_year, key_ID)
  
  lat_lon_haulid <- unique(reduced_year[,.(lat,lon,key_ID)])
  neus_distances <- distm(lat_lon_haulid[,.(lon,lat)])
  key_IDs <- lat_lon_haulid[,key_ID]

  colnames(neus_distances) <- rownames(neus_distances) <- key_IDs

  #wide to long
  haulid_distances.l <- reshape2::melt(neus_distances,varnames = (c("haulid1", "haulid2")), value.name = "distance")
  
  #make into data table
  haulid_distances.l <- data.table(haulid_distances.l)

  
  reduced_year_wide <- dcast(reduced_year, key_ID + year ~ matched_name2, value.var = "wtcpue", fun.aggregate = sum) #long to wide data for community matrix, column names are cell then species
  
  ncols <- ncol(reduced_year_wide)
  communitymatrix <- cbind(reduced_year_wide[,3:ncols], reduced_year_wide[,1:2]) #community matrix with year and cell on far right

  #list of haulid keys
  key_IDs_subset <- communitymatrix$key_ID

  dissimilarities_abundance <- vegdist(communitymatrix[,1:(ncols-2)], method = "bray", binary = F) #dissimilarity 
  dissimilarities_occurrence <- vegdist(communitymatrix[,1:(ncols-2)], method = "jaccard", binary = T) #T binary performs presence absence standardization before using decostand

  #make into matrix
  dissimilarities_abundance.m <- as.matrix(dissimilarities_abundance, labels=TRUE)
  dissimilarities_occurrence.m <- as.matrix(dissimilarities_occurrence, labels=TRUE)
  colnames(dissimilarities_abundance.m) <- rownames(dissimilarities_abundance.m) <- key_IDs_subset
  colnames(dissimilarities_occurrence.m) <- rownames(dissimilarities_occurrence.m) <- key_IDs_subset

  #reshape dissimilarities
  dissimilarities_abundance.l <- reshape2::melt(dissimilarities_abundance.m, varnames = c("haulid1", "haulid2"), value.name = "bray_curtis_dissimilarity")
  dissimilarities_occurrence.l <- reshape2::melt(dissimilarities_occurrence.m, varnames = c("haulid1", "haulid2"), value.name = "jaccard_dissimilarity")
  dissimilarities_abundance.l <- data.table(dissimilarities_abundance.l) #and then to data table
  dissimilarities_occurrence.l <- data.table(dissimilarities_occurrence.l)

  #add year for these values
  dissimilarities_abundance.l[, "year" := neus_years_fall[i]]
  dissimilarities_occurrence.l[, "year" := neus_years_fall[i]]

  #merge distance with dissimilarity for this year with both metrics of dissimilarity
  dissimilarities_full <- haulid_distances.l[dissimilarities_abundance.l, on = c("haulid1", "haulid2")]
  dissimilarities_full <- dissimilarities_full[dissimilarities_occurrence.l, on = c("haulid1", "haulid2", "year")]


  #add to data table
  neus_fall_distances_dissimilarities_allyears <- rbind(neus_fall_distances_dissimilarities_allyears, dissimilarities_full)
  
}

summary(neus_fall_distances_dissimilarities_allyears) #here we have bray, jaccard and geographic distance

#delete repeats
neus_fall_distances_dissimilarities_allyears <- neus_fall_distances_dissimilarities_allyears[haulid1 >= haulid2,] #******** to 1554337 rows


neus_fall_distances_dissimilarities_allyears[,bray_curtis_similarity := (1-bray_curtis_dissimilarity)][,jaccard_similarity := (1-jaccard_dissimilarity)]

saveRDS(neus_fall_distances_dissimilarities_allyears, file = "neus_fall_distances_dissimilarities_allyears.rds")

```

#Heat map

Subsample for plotting
```{r subsample}
#jaccard only
neus_fall_distances_dissimilarities_allyears_jaccard <- neus_fall_distances_dissimilarities_allyears[,.(year,distance,jaccard_similarity)]

#new column with rounded distance
neus_fall_distances_dissimilarities_allyears_jaccard[,distance_10s := round(distance,-1)] #round to nearest 100

#new column with median jaccard similarity
neus_fall_distances_dissimilarities_allyears_jaccard[, jaccard_similarity_mean := mean(jaccard_similarity), .(year, distance_10s)]

#reduce to unique values
neus_fall_distances_dissimilarities_allyears_jaccard_rounded <- unique(neus_fall_distances_dissimilarities_allyears_jaccard, by = c("year","distance_10s"))
```


All possible combos
```{r all combos}
#all possible 10s
seq_10 <- seq(0,max(neus_fall_distances_dissimilarities_allyears_jaccard_rounded$distance_10s), by = 10)

#datatable with all possible combos
neus_fall_distances_dissimilarities_allyears_jaccard_allcombos <- data.table(expand.grid(year = neus_years_fall, distance_10s = seq_10))

#combine
neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos <- neus_fall_distances_dissimilarities_allyears_jaccard_allcombos[neus_fall_distances_dissimilarities_allyears_jaccard_rounded, on = c("year","distance_10s")]
```


Trying to use ggplot
```{r}
ggplot(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos, aes(year, distance_10s, fill = jaccard_similarity_mean)) +
  geom_raster(interpolate = T) +
  theme_classic() +
  scale_fill_viridis(discrete = F)

library(sp)

```

Convert to matrix
```{r jaccard matrix}
neus_fall_distances_dissimilarities_allyears_jaccard_wide <-
data.table::dcast(neus_fall_distances_dissimilarities_allyears_jaccard_rounded[,.(year,distance_10s,jaccard_similarity_mean)], distance_10s ~ year, fill = NA)

setkey(neus_fall_distances_dissimilarities_allyears_jaccard_wide, distance_10s)

#get rid of first column
neus_fall_distances_dissimilarities_allyears_jaccard_wide.m <- neus_fall_distances_dissimilarities_allyears_jaccard_wide[,2:ncol(neus_fall_distances_dissimilarities_allyears_jaccard_wide)]

neus_fall_distances_dissimilarities_allyears_jaccard_wide.m <- as.matrix(neus_fall_distances_dissimilarities_allyears_jaccard_wide.m)

neus_fall_distances_dissimilarities_allyears_jaccard_wide.r <- as.raster (neus_fall_distances_dissimilarities_allyears_jaccard_wide.m)
```

Convert comprehensive table to matrix
```{r}
neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide <- data.table::dcast(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos[,.(year,distance_10s,jaccard_similarity_mean)], distance_10s ~ year, fill = NA)

setkey(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide, distance_10s)

#get rid of first column
neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.m <- neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide[,2:ncol(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide)]

neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.m <- as.matrix(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.m)

neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.r <- as.raster (neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.m)
```

Plot raster
```{r}
image(neus_fall_distances_dissimilarities_allyears_jaccard_rounded_allcombos_wide.r)
```
From "Depth-Time visualization using R, the tidyverse, and ggplot2" tutorial

```{r}

#jaccard similarity
ggplot(neus_fall_distances_dissimilarities_allyears,aes(year,distance, color = jaccard_similarity)) +
  geom_point() +
  scale_color_gradientn(colors =
c("purple" ,"blue"  , "green" , "yellow" ,"orange", "red")
  ) +
  labs(y = "Distance (m)", x = "Year", color = "Jaccard Similarity") +
  theme_classic()

#bray curtis similarity
ggplot(neus_fall_distances_dissimilarities_allyears,aes(year,distance, color = bray_curtis_similarity)) +
  geom_point() +
  scale_color_gradientn(colors =
c("purple" ,"blue"  , "green" , "yellow" ,"orange", "red")
  ) +
  labs(y = "Distance (m)", x = "Year", color = "Bray Curtis Similarity") +
  theme_classic()
```
Box plots
```{r}
#convert year to factor
setkey(neus_fall_distances_dissimilarities_allyears,year)
neus_fall_distances_dissimilarities_allyears[,year.f := as.factor(year)]

#jaccard similarity
ggplot(neus_fall_distances_dissimilarities_allyears,aes(year.f,jaccard_similarity)) +
  geom_boxplot(outlier.shape = NA) +
  labs(x="Year", y = "Jaccard Similarity") +
  scale_x_discrete(limits=levels(neus_fall_distances_dissimilarities_allyears$year.f)) +
  geom_smooth(method = "lm", se=FALSE, color="red", aes(group=1)) +
  ylim(c(0,0.75)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))

#bray curtis similarity
ggplot(neus_fall_distances_dissimilarities_allyears,aes(year.f,bray_curtis_similarity)) +
  geom_boxplot(outlier.shape = NA) +
  labs(x="Year", y = "Bray Curtis Similarity") +
  scale_x_discrete(limits=levels(neus_fall_distances_dissimilarities_allyears$year.f)) +
  geom_smooth(method = "lm", se=FALSE, color="red", aes(group=1)) +
  ylim(c(0,0.48)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90))
```
