---
title: "Single plot for all dissimilarities over time"
output: html_notebook
---

Single plot of dissimilarities over time for all regions

```{r setup}
library(data.table)
library(ggplot2)

#load models as objects (doesn't work right now)
jaccard_model_outputs <-readRDS(here::here("output","distance_decay","jaccard_model_outputs.rds"))
bray_model_outputs <- readRDS(here::here("output","distance_decay","bray_model_outputs.rds"))
#
##load full dissimilarity 
distances_dissimilarities_allyears <- readRDS(here::here("output","distance_decay","distances_dissimilarities_allyears.rds"))
```


Trying to plot all together
```{r average columns}

library(pals)
pal <- polychrome(n = 36)

distances_dissimilarities_allyears[,mean_yearly_jaccard := mean(jaccard_dissimilarity_turnover),.(year, season_survey)][,mean_yearly_bray := mean(bray_curtis_dissimilarity_balanced),.(year, season_survey)][,sd_yearly_jaccard := sd(jaccard_dissimilarity_turnover),.(year, season_survey)][,sd_yearly_bray := sd(bray_curtis_dissimilarity_balanced),.(year, season_survey)]

distances_dissimilarities_allyears.year <- unique(distances_dissimilarities_allyears[,.(year, season_survey, season, survey, mean_yearly_jaccard, sd_yearly_jaccard, mean_yearly_bray, sd_yearly_bray)])

distances_dissimilarities_allyears.year[,mean_jaccard := mean(mean_yearly_jaccard),.(year)][,mean_bray := mean(mean_yearly_bray),.(year)]


#merge model outputs with this summary table
distances_dissimilarities_allyears.year.models <- distances_dissimilarities_allyears.year[jaccard_model_outputs, on = c("survey", "season", "season_survey")]

distances_dissimilarities_allyears.year.models <- distances_dissimilarities_allyears.year.models[bray_model_outputs, on = c("survey", "season", "season_survey")]

distances_dissimilarities_allyears.year.models[,mean_jaccard := mean(mean_yearly_jaccard),.(year)][,mean_bray := mean(mean_yearly_bray),.(year)]

#save these means
saveRDS(distances_dissimilarities_allyears.year.models, here::here("output","distance_decay","distances_dissimilarities_allyears.year.models.rds"))


#add column to see if relationship is significant
distances_dissimilarities_allyears.year.models[, bray_significant := ifelse(bray_coef_pvalue<0.05, T,F)][,homog_differ_bray := ifelse(bray_coef > 0 & bray_significant == T, "Differentiation", ifelse(bray_coef < 0 & bray_significant == T, "Homogenization", "No Significant Change"))]
distances_dissimilarities_allyears.year.models[, jaccard_significant := ifelse(jaccard_coef_pvalue<0.05, T,F)][,homog_differ_jaccard := ifelse(jaccard_coef > 0 & jaccard_significant == T, "Differentiation", ifelse(jaccard_coef < 0 & jaccard_significant == T, "Homogenization", "No Significant Change"))]



#jaccard
ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_jaccard, color = season_survey), se = F, method = "glm",size = 0.5, alpha = 0.5,  stat = "smooth") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = year, y = mean_jaccard), se =F, method = "glm", color  ="black") +
  labs(y = "Mean Annual Jaccard Dissimilarity", x = "Year") +
  theme_classic()+
  theme(legend.position = "none")

ggsave(path = here::here("figures","distance_decay"), filename =   "mean_annual_jaccard_dissimilarity_full_plot.jpg",  width = 8, height = 4, unit = "in")

#bray

ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_bray, color = season_survey), se = F, method = "glm",size = 0.5, alpha = 0.5,  stat  =  "smooth") +
#  geom_ribbon(aes(ymin = mean_yearly_bray - sd_yearly_bray, ymax = mean_yearly_bray + sd_yearly_bray)) +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
    geom_smooth(aes(x = year, y = mean_bray), se =F, method = "glm", color  ="black") +
  labs(y = "Mean Annual Bray Curtis Dissimilarity", x = "Year") +
  theme_classic()+
  theme(legend.position = "none")

ggsave(path = here::here("figures","distance_decay"), filename =   "mean_annual_bray_dissimilarity_full_plot.jpg",  width = 8, height = 4, unit = "in")
```

Same, but with legend
```{r full plot with legend}
#jaccard
ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_jaccard, color = season_survey), se = F, method = "glm",size = 0.5, alpha = 0.5,  stat = "smooth") +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
  geom_smooth(aes(x = year, y = mean_jaccard), se =F, method = "glm", color  ="black") +
  labs(y = "Mean Annual Jaccard Dissimilarity", x = "Year") +
  theme_classic()

ggsave(path = here::here("figures","distance_decay"), filename =   "mean_annual_jaccard_dissimilarity_full_plot_wlegend.jpg")

#bray

ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_bray, color = season_survey), se = F, method = "glm",size = 0.5, alpha = 0.5,  stat  =  "smooth") +
#  geom_ribbon(aes(ymin = mean_yearly_bray - sd_yearly_bray, ymax = mean_yearly_bray + sd_yearly_bray)) +
  scale_color_manual(values =  c("#5A5156","#E4E1E3","#F6222E","#FE00FA", 
  "#16FF32","#3283FE","#FEAF16","#B00068", 
  "#1CFFCE","#90AD1C","#2ED9FF","#DEA0FD", 
  "#AA0DFE","#F8A19F","#325A9B","#C4451C", 
  "#1C8356","#85660D","#B10DA1","#FBE426", 
  "#1CBE4F","#FA0087","#FC1CBF","#F7E1A0", 
  "#C075A6","#782AB6","#AAF400","#BDCDFF", 
  "#822E1C","#B5EFB5","#7ED7D1","#1C7F93", 
  "#D85FF7","#683B79","#66B0FF","#3B00FB")) +
    geom_smooth(aes(x = year, y = mean_bray), se =F, method = "glm", color  ="black") +
  labs(y = "Mean Annual Bray Curtis Dissimilarity", x = "Year") +
  theme_classic()

ggsave(path = here::here("figures","distance_decay"), filename =   "mean_annual_bray_dissimilarity_full_plot_wlegend.jpg")
```

Same plots but color by significance or not and homogenization or not

```{r}
#jaccard (look more closely, some are coding wrong)
mean_annual_jaccard_dissimilarity_full_plot_homogdiffer <- ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_jaccard, group = season_survey, color = homog_differ_jaccard), se = F, method = "glm",size = 0.5,  stat = "smooth") +
  scale_color_manual(values =  c("#F8A19F","#3283FE", "gray")) +
  labs(y = "Mean Annual Jaccard Dissimilarity", x = "Year") +
  theme_classic()

mean_annual_jaccard_dissimilarity_full_plot_homogdiffer

ggsave(mean_annual_jaccard_dissimilarity_full_plot_homogdiffer, path = here::here("figures","distance_decay"), filename =   "mean_annual_jaccard_dissimilarity_full_plot_homogdiffer.jpg",  width = 8, height = 4, unit = "in")

#nolegend
ggsave(mean_annual_jaccard_dissimilarity_full_plot_homogdiffer + theme(legend.position = "none"), path = here::here("figures","distance_decay"), filename =   "mean_annual_jaccard_dissimilarity_full_plot_homogdiffer_nolegend.jpg",  width = 8, height = 4, unit = "in")

#bray

mean_annual_bray_dissimilarity_full_plot_homogdiffer <- ggplot(distances_dissimilarities_allyears.year.models) +
  geom_line(aes(x = year, y = mean_yearly_bray, group = season_survey, color = homog_differ_bray), se = F, method = "glm",size = 0.5, alpha = 0.5,  stat  =  "smooth") +
#  geom_ribbon(aes(ymin = mean_yearly_bray - sd_yearly_bray, ymax = mean_yearly_bray + sd_yearly_bray)) +
  scale_color_manual(values =  c("#F8A19F","#3283FE", "gray")) +
  labs(y = "Mean Annual Bray Curtis Dissimilarity", x = "Year") +
  theme_classic()
#+
#  theme(legend.position = "none")

mean_annual_bray_dissimilarity_full_plot_homogdiffer

ggsave(mean_annual_bray_dissimilarity_full_plot_homogdiffer, path = here::here("figures","distance_decay"), filename =   "mean_annual_bray_dissimilarity_full_plot_homogdiffer.jpg",  width = 8, height = 4, unit = "in")

#nolegend
ggsave(mean_annual_bray_dissimilarity_full_plot_homogdiffer + theme(legend.position = "none"), path = here::here("figures","distance_decay"), filename =   "mean_annual_bray_dissimilarity_full_plot_homogdiffer_nolegend.jpg",  width = 8, height = 4, unit = "in")
```

